config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
  get 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:delete, :get]

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :wants, foreign_key: :wanting_user_id
	has_many :wanted_by, :class => Want , foreign_key: :wanted_user_id

	# scope :possible_matches, -> { where(published: true) }

	def possible_matches
		User.all - self.matches - [self]
	end

	def matches
		arr = []
		user_id = self.id
		self.wants.each do |want|
			user = User.find(want.wanted_user_id)
			if user.wants.map(&:wanted_user_id).include?(user_id)
				arr << user
			end
		end
		arr
	end

	def want!(wanted_user_id)
		self.wants.create(wanted_user_id: wanted_user_id)
	end

	def wants?(user_id)
		wants.where(wanted_user_id: user_id)
	end

	def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.email = auth.info.email
	    user.gender = auth.extra.raw_info.gender
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.save!
	  end
	end
end

app/models/want.rb
class Want < ActiveRecord::Base
	belongs_to :user, foreign_key: :wanting_user_id

	validates_uniqueness_of :wanting_user_id, :scope => :wanted_user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
		session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/welcom_controller.rb
class WelcomController < ApplicationController
	def index
		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeldmanTinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out", method: :delete %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>